spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:mysql://mysql:3306/quizservice_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Nrm1223#nrm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8083
  servlet:
    context-path: /api/quizzes
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    narimanCode: DEBUG