name: CI Pipeline
on:
  push:
    branches:
      - main
      - user-service
      - quiz-service
      - notification-service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build user-service
        run: mvn -B package --file user-service/pom.xml -DskipTests
      - name: Build quiz-service
        run: mvn -B package --file quiz-service/pom.xml -DskipTests
      - name: Build notification-service
        run: mvn -B package --file notification-service/pom.xml -DskipTests