name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - user-service
      - quiz-service
      - notification-service

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f user-service/pom.xml clean package

      - name: Run tests
        run: mvn -f user-service/pom.xml test